# Generated by Django 2.1 on 2018-08-28 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0004_author_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
