# Generated by Django 2.1 on 2018-08-28 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0005_auto_20180828_2252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
